import React from 'react';
const value=v=>v==null?'Unknown':String(v);
export default function RiskDetails({risk,busy}){
 if(busy)return <div className="live-risk" role="status">Fetching selected-token provider reports and RPC checks…</div>;
 if(!risk)return null;
 if(risk.error)return <div className="live-risk" role="status">Risk report unavailable: {risk.error}</div>;
 const a=risk.authorities||{},t=risk.token2022||{},l=risk.liquidity||{},h=risk.holders||{},b=risk.bundling||{};
 const checked=risk.providers?.rpc==='live';
 const rows=[['Mint authority',a.status==='unknown'?'Unknown':a.mint||'Revoked'],['Freeze authority',a.status==='unknown'?'Unknown':a.freeze||'Disabled'],['LP custody',l.state||'unknown'],['Reported LP locked',l.lockedPct==null?'Unknown':`${l.lockedPct}%`],['Reported unlock date',l.unlockAt?new Date(l.unlockAt).toLocaleString():'Unknown'],['Pools in report',value(l.pools)],['Top 10 reported holders',h.top10Bps==null?'Unknown':`${(h.top10Bps/100).toFixed(2)}% (pool accounts may be included)`],['Insiders detected',value(b.insiders)],['Bundled supply',b.bundledPct==null?'Unknown':`${(b.bundledPct/100).toFixed(2)}%`],['Bundle assessment',b.state||'unknown'],['Token-2022',checked?(t.enabled?'Yes':'No'):'Unknown'],[checked&&t.enabled?'Highest configured fee rate':'Reported fee rate',t.transferFeeBps==null?'Unknown':`${t.transferFeeBps/100}%`],['Fee update authority',t.feeAuthority||'Not reported'],['Permanent delegate',t.permanentDelegate||(checked?'Not present':'Unknown')],['Default frozen',checked?(t.defaultFrozen?'Yes':'No'):'Unknown'],['Transfer hook',t.transferHook||(checked?'Not present':'Unknown')],['Reported rugged',risk.rugged==null?'Unknown':risk.rugged?'Yes':'No']];
 return <section className="live-risk risk-details" aria-label="Detailed live token risk"><div role="status"><h3>{risk.safe===false?'Risk detected':risk.safe===true?'Available checks passed':'Incomplete assessment'}</h3><strong>Provider score: {risk.score??'Unavailable'}</strong><p>Provider score is not a probability or an Astra 1–10 rating. No score is invented for missing data.</p><small>Report fetched {new Date(risk.at).toLocaleString()} · provider data may lag the chain</small></div><div className="risk-providers">{Object.entries(risk.providers||{}).map(([name,status])=><span key={name}>{name}: <b>{status==='live'?'Responded':'Unavailable'}</b></span>)}</div><h3>Findings · {risk.risks?.length||0}</h3>{risk.risks?.length?<ul>{risk.risks.map((r,i)=><li key={i}><span className="risk-severity">{r.level}</span><strong>{r.name}</strong><p>{r.description||'No further explanation supplied by provider.'}</p></li>)}</ul>:<p>No findings supplied. Missing findings do not prove safety.</p>}<dl>{rows.map(([label,text])=><React.Fragment key={label}><dt>{label}</dt><dd>{text}</dd></React.Fragment>)}</dl><p>Unavailable checks remain unknown. {checked&&t.enabled?'The fee rate is the highest configured value across both on-chain schedules; it does not select an active epoch or apply the per-transfer maximum.':'Fee rate and authority fields may reflect external provider data when Token-2022 mint evidence is unavailable.'} LP percentages and holder concentration reflect provider data, not independently verified executable liquidity.</p></section>;
}
