import test from 'node:test';
import assert from 'node:assert/strict';
import { Keypair, PublicKey, SystemProgram, TransactionMessage, VersionedMessage, VersionedTransaction } from '@solana/web3.js';
import bs58 from 'bs58';
import { CertifiedLiveExecutionCoordinator } from '../../dist/platform/execution/certified-live-coordinator.js';
import { assembleVerifiedTransaction } from '../../dist/platform/execution/transaction-artifact.js';
const key = Keypair.fromSeed(new Uint8Array(32).fill(42));
function message(version=0, extra=false) {
  const instructions=[SystemProgram.transfer({fromPubkey:key.publicKey,toPubkey:PublicKey.default,lamports:1})];
  if(extra) instructions.push(SystemProgram.transfer({fromPubkey:Keypair.fromSeed(new Uint8Array(32).fill(43)).publicKey,toPubkey:PublicKey.default,lamports:1}));
  const m=new TransactionMessage({payerKey:key.publicKey,recentBlockhash:PublicKey.default.toBase58(),instructions});
  return (version===0?m.compileToV0Message():m.compileToLegacyMessage()).serialize();
}
function sign(bytes,k=key){const tx=new VersionedTransaction(VersionedMessage.deserialize(bytes));tx.sign([k]);return tx.signatures[0];}
function harness(signFn=async b=>sign(b), sendFn=async w=>bs58.encode(VersionedTransaction.deserialize(w).signatures[0])) {
  let signCalls=0,sendCalls=0;
  const gateway={publicKey:key.publicKey,signTransactionMessage:async b=>{signCalls++;return signFn(b);}};
  const coordinator=new CertifiedLiveExecutionCoordinator({MODE:'live'},{endpoints:[{rpcEndpoint:'offline'}],connection:{sendRawTransaction:async w=>{sendCalls++;return sendFn(w);}}},{},gateway);
  const seal=(bytes=message())=>coordinator.sealExecutionAuthorizationRoot({intentId:'i',generation:1,reservationId:'r',candidateTransactionBytes:bytes,simulationComputeUnits:1,estimatedNetSolDelta:0n,expiresAtBlockHeight:10});
  return {coordinator,seal,gateway,calls:()=>({signCalls,sendCalls})};
}
test('single signer legacy/v0 artifacts have verified signatures and immutable string identities',()=>{for(const v of ['legacy',0]){const b=message(v);const a=assembleVerifiedTransaction(b,sign(b),key.publicKey);assert.ok(Object.isFrozen(a));assert.equal(a.signature,bs58.encode(VersionedTransaction.deserialize(Buffer.from(a.wireBase64,'base64')).signatures[0]));}});
test('malformed, trailing, unsupported and multisigner messages are rejected before signer invocation',()=>{for(const bytes of [new Uint8Array([1]),new Uint8Array([...message(),0]),new Uint8Array([0x81,...message().slice(1)]),message(0,true)]){const h=harness();assert.throws(()=>h.seal(bytes));assert.equal(h.calls().signCalls,0);}});
test('wrong or malformed signatures never become signed artifacts',async()=>{for(const bad of [new Uint8Array(63),new Uint8Array(64)]){const h=harness(async()=>bad);await assert.rejects(h.coordinator.invokeCertifiedSigning(h.seal()),/SIGNATURE_INVALID/);assert.equal(h.calls().sendCalls,0);}});
test('sealing snapshots caller bytes and getter returns defensive copies',async()=>{const h=harness();const b=message();const original=Uint8Array.from(b);const root=h.seal(b);b.fill(0);root.candidateTransactionBytes.fill(0);const wire=await h.coordinator.invokeCertifiedSigning(root);assert.deepEqual(VersionedTransaction.deserialize(wire).message.serialize(),original);});
test('gateway mutation across await cannot change sealed bytes or expected key',async()=>{let release;const barrier=new Promise(r=>release=r);let received;const h=harness(async b=>{received=b;await barrier;return sign(message());});const root=h.seal();const promise=h.coordinator.invokeCertifiedSigning(root);received.fill(0);h.gateway.publicKey=PublicKey.default;release();const wire=await promise;assert.deepEqual(VersionedTransaction.deserialize(wire).message.serialize(),message());});
test('fabricated roots are rejected and concurrent PREPARED signing does not redispatch',async()=>{let release;const wait=new Promise(r=>release=r);const h=harness(async b=>{await wait;return sign(b);});const root=h.seal();await assert.rejects(h.coordinator.invokeCertifiedSigning({...root}),/NOT_ISSUED/);const first=h.coordinator.invokeCertifiedSigning(root);await assert.rejects(h.coordinator.invokeCertifiedSigning(root),/OUTCOME_UNKNOWN/);release();await first;assert.equal(h.calls().signCalls,1);});
test('submission binds exact signed generation and snapshots bytes before await',async()=>{let release;const wait=new Promise(r=>release=r);let received;const h=harness(undefined,async w=>{received=w;await wait;return bs58.encode(VersionedTransaction.deserialize(w).signatures[0]);});const wire=await h.coordinator.invokeCertifiedSigning(h.seal());const sig=bs58.encode(VersionedTransaction.deserialize(wire).signatures[0]);await assert.rejects(h.coordinator.submitExactBytes('i',1,wire,'fake'),/ARTIFACT_MISMATCH/);await assert.rejects(h.coordinator.submitExactBytes('i',2,wire,sig),/ARTIFACT_MISMATCH/);const pending=h.coordinator.submitExactBytes('i',1,wire,sig);wire.fill(0);assert.notEqual(received[0],0);release();assert.equal(await pending,sig);assert.equal(h.calls().sendCalls,1);});
test('RPC mismatch and accepted timeout remain ambiguous and cannot resume dispatch',async()=>{for(const send of [async()=> 'wrong',async()=>{throw Error('accepted response lost');}]){const h=harness(undefined,send);const wire=await h.coordinator.invokeCertifiedSigning(h.seal());const sig=bs58.encode(VersionedTransaction.deserialize(wire).signatures[0]);await assert.rejects(h.coordinator.submitExactBytes('i',1,wire,sig));await assert.rejects(h.coordinator.submitExactBytes('i',1,wire,sig),/OUTCOME_UNKNOWN/);assert.equal(h.calls().sendCalls,1);}});
test('valid signature for another message or key is rejected',()=>{const b=message();const other=message('legacy');assert.throws(()=>assembleVerifiedTransaction(b,sign(other),key.publicKey),/SIGNATURE_INVALID/);const wrongKey=Keypair.fromSeed(new Uint8Array(32).fill(44));const wrongMessage=new TransactionMessage({payerKey:wrongKey.publicKey,recentBlockhash:PublicKey.default.toBase58(),instructions:[]}).compileToV0Message().serialize();assert.throws(()=>assembleVerifiedTransaction(b,sign(wrongMessage,wrongKey),key.publicKey),/SIGNATURE_INVALID/);});
test('mutated submitted bytes never reach RPC',async()=>{const h=harness();const wire=await h.coordinator.invokeCertifiedSigning(h.seal());const sig=bs58.encode(VersionedTransaction.deserialize(wire).signatures[0]);wire[wire.length-1]^=1;await assert.rejects(h.coordinator.submitExactBytes('i',1,wire,sig),/ARTIFACT_MISMATCH/);assert.equal(h.calls().sendCalls,0);});

test('legacy and v0 header/index corruption is rejected before signing',()=>{for(const version of ['legacy',0])for(const mutate of [m=>m.header.numReadonlySignedAccounts=1,m=>m.header.numReadonlySignedAccounts=2,m=>m.header.numReadonlyUnsignedAccounts=250,m=>m.compiledInstructions[0].programIdIndex=0,m=>m.compiledInstructions[0].programIdIndex=250,m=>m.compiledInstructions[0].accountKeyIndexes[0]=250]){const m=VersionedMessage.deserialize(message(version));if(version==='legacy'){// Legacy getters allocate compiled instruction views; mutate its wire-native fields instead below.
if(mutate.toString().includes('programIdIndex=0'))m.instructions[0].programIdIndex=0;
else if(mutate.toString().includes('programIdIndex=250'))m.instructions[0].programIdIndex=250;
else if(mutate.toString().includes('accountKeyIndexes'))m.instructions[0].accounts[0]=250;
else mutate(m);
}else mutate(m);const h=harness();assert.throws(()=>h.seal(m.serialize()),/HEADER_INVALID|INDEX_INVALID/);assert.equal(h.calls().signCalls,0);}});
test('wire size checked before signature and exact packet boundary accepted',()=>{for(const length of [1167,1168]){const m=VersionedMessage.deserialize(message());const overhead=m.serialize().length-m.compiledInstructions[0].data.length; m.compiledInstructions[0].data=new Uint8Array(length-overhead-1);const bytes=m.serialize();assert.equal(bytes.length,length);const h=harness();if(length===1167)assert.doesNotThrow(()=>h.seal(bytes));else assert.throws(()=>h.seal(bytes),/PACKET_TOO_LARGE/);assert.equal(h.calls().signCalls,0);}});
test('v0 lookup index cardinality is checked while ALT contents remain unverified',()=>{const m=VersionedMessage.deserialize(message());m.addressTableLookups=[{accountKey:PublicKey.default,writableIndexes:[0],readonlyIndexes:[1]}];m.compiledInstructions[0].accountKeyIndexes=[m.staticAccountKeys.length+1];const h=harness();assert.doesNotThrow(()=>h.seal(m.serialize()));m.compiledInstructions[0].accountKeyIndexes=[m.staticAccountKeys.length+2];assert.throws(()=>h.seal(m.serialize()),/INDEX_INVALID/);m.compiledInstructions[0].accountKeyIndexes=[0];m.addressTableLookups[0].writableIndexes=Array(254).fill(0);assert.throws(()=>h.seal(m.serialize()),/ACCOUNT_COUNT_INVALID/);assert.equal(h.calls().signCalls,0);});
