import { readFile, mkdir, rename, appendFile, stat } from 'node:fs/promises';
import { dirname } from 'node:path';
import type { TokenRow } from './market-hub.js';

export type PaperPosition = { mint: string; symbol: string; name: string; qty: number; entryUsd: number; cost: string; opened: number; peakUsd: number; stage: number; mark: { value: string; at: number } | null; panic: boolean; strategy: string };
type Fill = { at: number; mint: string; symbol: string; side: 'buy' | 'sell'; lamports: string; pnl: string; reason: string; priceUsd?: number; solPriceUsd?: number; liquidityUsd?: number | null; volume24hUsd?: number | null; change24hPct?: number | null; marketCapUsd?: number | null; pair?: string | null; dex?: string | null; safety?: string };
type Disk = { version: 1; cash: string; positions: Record<string, PaperPosition>; fills: Fill[]; realized: string; since: number; halted: boolean; losses: number; paused: boolean; autoPaper?: boolean; autoUsed?: string[] };
const LAMPORTS_PER_SOL = 1_000_000_000;
const CSV_HEADER = ['timestamp_utc','event','side','mint','symbol','name','strategy','price_usd','sol_price_usd','liquidity_usd','volume_24h_usd','change_24h_pct','market_cap_usd','pair','dex','cost_lamports','proceeds_lamports','pnl_lamports','reason','safety'].join(',') + '\n';
const initial = (): Disk => ({ version: 1, cash: String(10 * LAMPORTS_PER_SOL), positions: {}, fills: [], realized: '0', since: Date.now(), halted: false, losses: 0, paused: false, autoPaper: false, autoUsed: [] });
const solPrice = (tokens: TokenRow[]) => tokens.find(t => t.symbol.toUpperCase() === 'SOL' && t.price !== null)?.price ?? null;
const csv = (value: unknown) => { const text = value === null || value === undefined ? '' : String(value); return /[",\n]/.test(text) ? '"' + text.replaceAll('"', '""') + '"' : text; };
const number = (value: number | null | undefined) => value === null || value === undefined || !Number.isFinite(value) ? '' : String(value);
const fillCsvRow = (fill: Fill, name = '') => [new Date(fill.at).toISOString(), fill.side, fill.side, fill.mint, fill.symbol, name, fill.reason.includes('auto') ? 'auto-paper' : fill.reason.includes('test') ? 'simulator-test' : 'manual-paper', number(fill.priceUsd), number(fill.solPriceUsd), number(fill.liquidityUsd), number(fill.volume24hUsd), number(fill.change24hPct), number(fill.marketCapUsd), fill.pair, fill.dex, fill.side === 'buy' ? String(-BigInt(fill.lamports)) : '', fill.side === 'sell' ? fill.lamports : '', fill.pnl, fill.reason, fill.safety].map(csv).join(',');

export class PaperPortfolio {
  private state: Disk = initial(); private write: Promise<void> = Promise.resolve(); private csvWrite: Promise<void> = Promise.resolve(); private tickTask: Promise<void> | null = null; private autoUsed = new Set<string>();
  constructor(private file: string, private maxPositions = 3, private buyLamports = 100_000_000, private csvFile = file.replace(/\.json$/i, '_trades.csv')) {}
  async start() {
    try {
      const x = JSON.parse(await readFile(this.file, 'utf8'));
      const validInt = (v: unknown) => typeof v === 'string' && /^-?\d+$/.test(v);
      const valid = x?.version === 1 && validInt(x.cash) && validInt(x.realized) && x.positions && typeof x.positions === 'object' && !Array.isArray(x.positions) && Array.isArray(x.fills) && x.fills.length <= 300 && x.fills.every((f: any) => f && validInt(f.lamports) && validInt(f.pnl) && Number.isFinite(f.at) && f.at > 0);
      if (valid) this.state = { ...initial(), ...x, autoUsed: Array.isArray(x.autoUsed) ? x.autoUsed.filter((m: unknown): m is string => typeof m === 'string').slice(-1000) : [] };
    } catch { /* Corrupt snapshots fall back to a clean paper wallet. */ }
    if (!this.state.since) this.state.since = Date.now(); this.autoUsed = new Set(this.state.autoUsed ?? []); try { await stat(this.csvFile); } catch { if (this.state.fills.length) await appendFile(this.csvFile, CSV_HEADER + this.state.fills.map(fill => fillCsvRow(fill)).join('\n') + '\n', 'utf8'); }
  }
  async setPaused(paused: boolean) { this.state.paused = paused; await this.persist(); }
  async setAutoPaper(enabled: boolean) { this.state.autoPaper = enabled; if (!enabled) this.state.autoUsed = [...this.autoUsed]; await this.persist(); }
  private persist() { const value = JSON.stringify(this.state, null, 2) + '\n'; this.write = this.write.catch(() => {}).then(async () => { await mkdir(dirname(this.file), { recursive: true }); const tmp = this.file + '.tmp'; await Bunless.write(tmp, value); await rename(tmp, this.file); }); return this.write; }
  snapshot(tokens: TokenRow[]) { const sol = solPrice(tokens); const positions = Object.values(this.state.positions).map(p => { const t = tokens.find(x => x.mint === p.mint); const mark = t?.price !== null && t?.price !== undefined && sol && p.entryUsd > 0 ? Math.max(0, Math.round(Number(BigInt(p.cost)) * (t.price / p.entryUsd) * (sol / (sol || 1)))) : null; if (mark !== null) p.mark = { value: String(mark), at: Date.now() }; return p; }); const unrealized = positions.reduce((n, p) => n + (p.mark ? BigInt(p.mark.value) - BigInt(p.cost) : 0n), 0n); return { mode: 'paper', demo: false, connected: false, paperActive: true, wallet: 'PAPER-SIMULATION', time: Date.now(), startedAt: this.state.since, paused: this.state.paused, halted: this.state.halted, autoPaper: !!this.state.autoPaper, csvFile: this.csvFile, stopping: false, feed: { healthy: tokens.length > 0, last: Date.now(), slot: 0 }, cash: this.state.cash, dayPnl: this.state.realized, day: new Date().toISOString().slice(0, 10), positions, pending: null, candidates: [], events: this.state.fills.slice(-30).reverse().map(f => ({ time: new Date(f.at).toISOString(), event: 'paper_' + f.side, mint: f.mint, side: f.side, reason: f.reason })), performance: { since: this.state.since, realized: this.state.realized, fills: this.state.fills, count: this.state.fills.length }, limits: { positions: this.maxPositions, exposure: String(this.maxPositions * this.buyLamports), dailyLoss: String(3 * this.buyLamports), buy: String(this.buyLamports), slippage: 1500, stop: 1200, tip: '0', priority: '0' }, unrealized: String(unrealized) }; }
  private async appendCsv(event: 'buy' | 'sell', token: TokenRow, fill: Fill, cost: string, proceeds: string, safety: string) { const row = [new Date(fill.at).toISOString(), event, fill.side, token.mint, token.symbol, token.name, fill.reason.includes('auto') ? 'auto-paper' : fill.reason.includes('test') ? 'simulator-test' : 'manual-paper', number(token.price), number(fill.solPriceUsd), number(token.liquidity), number(token.volume), number(token.change), number(token.cap), token.pair, token.dex, cost, proceeds, fill.pnl, fill.reason, safety].map(csv).join(',') + '\n'; this.csvWrite = this.csvWrite.catch(() => {}).then(async () => { await mkdir(dirname(this.csvFile), { recursive: true }); let exists = true; try { await stat(this.csvFile); } catch { exists = false; } await appendFile(this.csvFile, (exists ? '' : CSV_HEADER) + row, 'utf8'); }); await this.csvWrite; }
  async buy(token: TokenRow, tokens: TokenRow[], strategy = 'manual-paper') { if (this.state.paused || this.state.halted) throw new Error('Paper entries are paused or halted'); if (Object.keys(this.state.positions).length >= this.maxPositions) throw new Error('Paper position cap reached'); if (this.state.positions[token.mint]) throw new Error('One paper trade per token'); if (token.price === null || token.price <= 0) throw new Error('Token has no indexed price'); const sol = solPrice(tokens); if (!sol) throw new Error('SOL price unavailable'); const cost = BigInt(this.buyLamports); if (BigInt(this.state.cash) < cost) throw new Error('Paper cash exhausted'); const at = Date.now(); const safety = strategy.includes('unsafe') ? 'bypassed-for-test' : strategy.includes('cleared') || strategy.includes('auto') ? 'passed' : 'not-run'; const p: PaperPosition = { mint: token.mint, symbol: token.symbol, name: token.name, qty: this.buyLamports / token.price, entryUsd: token.price, cost: String(cost), opened: at, peakUsd: token.price, stage: 0, mark: null, panic: false, strategy }; this.state.positions[token.mint] = p; this.state.cash = String(BigInt(this.state.cash) - cost); const fill: Fill = { at, mint: token.mint, symbol: token.symbol, side: 'buy', lamports: String(-cost), pnl: '0', reason: strategy, priceUsd: token.price, solPriceUsd: sol, liquidityUsd: token.liquidity, volume24hUsd: token.volume, change24hPct: token.change, marketCapUsd: token.cap, pair: token.pair, dex: token.dex, safety }; this.state.fills.push(fill); await this.persist(); await this.appendCsv('buy', token, fill, String(cost), '0', safety); return this.snapshot(tokens); }
  async sell(mint: string, tokens: TokenRow[], fraction = 10000, reason = 'manual-paper') { const p = this.state.positions[mint]; if (!p) throw new Error('No paper position'); const token = tokens.find(x => x.mint === mint); const sol = solPrice(tokens); if (!token?.price || !sol) throw new Error('Current token or SOL price unavailable'); const frac = Math.max(1, Math.min(10000, Math.floor(fraction))); const proceeds = BigInt(Math.max(0, Math.round(Number(BigInt(p.cost)) * (token.price / p.entryUsd) * frac / 10000))); const basis = BigInt(p.cost) * BigInt(frac) / 10000n; const pnl = proceeds - basis; const at = Date.now(); this.state.cash = String(BigInt(this.state.cash) + proceeds); this.state.realized = String(BigInt(this.state.realized) + pnl); p.cost = String(BigInt(p.cost) - basis); p.qty *= (10000 - frac) / 10000; p.stage += 1; const fill: Fill = { at, mint, symbol: p.symbol, side: 'sell', lamports: String(proceeds), pnl: String(pnl), reason, priceUsd: token.price, solPriceUsd: sol, liquidityUsd: token.liquidity, volume24hUsd: token.volume, change24hPct: token.change, marketCapUsd: token.cap, pair: token.pair, dex: token.dex, safety: 'position-opened' }; this.state.fills.push(fill); if (frac === 10000 || BigInt(p.cost) === 0n) delete this.state.positions[mint]; await this.persist(); await this.appendCsv('sell', token, fill, String(basis), String(proceeds), 'position-opened'); return this.snapshot(tokens); }
  async tick(tokens: TokenRow[], safety?: (mint: string) => Promise<{ safe: boolean | null }>) { if (this.tickTask) return this.tickTask; this.tickTask = this.tickInternal(tokens, safety); try { await this.tickTask; } finally { this.tickTask = null; } }
  private async tickInternal(tokens: TokenRow[], safety?: (mint: string) => Promise<{ safe: boolean | null }>) {
    for (const p of Object.values(this.state.positions)) {
      const token = tokens.find(t => t.mint === p.mint); if (!token?.price || p.entryUsd <= 0) continue;
      const ratio = token.price / p.entryUsd; p.peakUsd = Math.max(p.peakUsd, token.price);
      if (ratio <= 0.88) { await this.sell(p.mint, tokens, 10000, 'strict-stop-12pct'); continue; }
      if (p.stage === 0 && ratio >= 2) { await this.sell(p.mint, tokens, 5000, 'take-profit-2x'); continue; }
      if (p.stage === 0 && ratio >= 1.2) { await this.sell(p.mint, tokens, 5000, 'take-profit-20pct'); continue; }
      if (p.stage === 1 && ratio >= 1.5) { await this.sell(p.mint, tokens, 5000, 'take-profit-50pct'); continue; }
      const peak = p.peakUsd / p.entryUsd;
      const trail = peak >= 6 ? 0.40 : peak >= 2.5 ? 0.35 : peak >= 1.5 ? 0.30 : peak >= 1.2 ? 0.25 : 0.20;
      const floor = peak >= 6 ? 2 : peak >= 2.5 ? 1.5 : peak >= 1.5 ? 1.2 : 1.05;
      if (peak >= 1.2 && ratio <= peak * (1 - trail) && ratio >= floor) { await this.sell(p.mint, tokens, 10000, 'dynamic-trailing-stop'); continue; }
      if (p.stage > 0 && ratio <= 1.02) await this.sell(p.mint, tokens, 10000, 'breakeven-protect');
    }
    if (this.state.autoPaper && !this.state.paused && !this.state.halted && Object.keys(this.state.positions).length < this.maxPositions && safety) {
      const now = Date.now();
      const candidates = tokens.filter(t => t.mint !== 'So11111111111111111111111111111111111111112' && t.price !== null && t.price > 0 && !this.state.positions[t.mint] && !this.autoUsed.has(t.mint) && now - t.at < 90_000 && (t.liquidity ?? 0) >= 50_000 && (t.volume ?? 0) >= 100_000 && t.change !== null && t.change >= -10 && t.change <= 250).sort((a, b) => (((b.volume ?? 0) / Math.max(1, b.liquidity ?? 1)) * (1 + Math.max(0, b.change ?? 0) / 100)) - (((a.volume ?? 0) / Math.max(1, a.liquidity ?? 1)) * (1 + Math.max(0, a.change ?? 0) / 100))).slice(0, 3);
      for (const token of candidates) { try { const check = await safety(token.mint); if (check.safe === true) { await this.buy(token, tokens, 'auto-paper-cleared'); this.autoUsed.add(token.mint); while (this.autoUsed.size > 1000) this.autoUsed.delete(this.autoUsed.values().next().value!); this.state.autoUsed = [...this.autoUsed]; break; } } catch { /* provider gaps do not create a trade */ } }
    }
    await this.persist();
  }
  async clear() { this.state = initial(); await this.persist(); }
}

const Bunless = { write: async (file: string, value: string) => { const { writeFile } = await import('node:fs/promises'); await writeFile(file, value, 'utf8'); } };
