const $ = id => document.getElementById(id);
const token = document.querySelector('meta[name="dashboard-token"]').content;
let state, busy = false, toastTimer, selectedToken = null;
function ensurePaperUi() {
  if (!$('risk-card')) { const card = document.createElement('div'); card.id = 'risk-card'; card.className = 'risk-card'; card.hidden = true; $('market-note').after(card); }
  const head = document.querySelector('#positions table thead tr');
  if (head && !head.querySelector('[data-paper-action-head]')) { const th = text('th', 'Paper action'); th.dataset.paperActionHead = '1'; head.append(th); }
}
const short = s => s ? s.slice(0, 5) + '…' + s.slice(-5) : '—';
function sol(raw) { const n = BigInt(raw ?? '0'), sign = n < 0n ? '−' : '', a = n < 0n ? -n : n; return sign + (a / 1000000000n) + '.' + (a % 1000000000n).toString().padStart(9, '0').slice(0, 5); }
function text(tag, value, cls) { const e = document.createElement(tag); e.textContent = value; if (cls) e.className = cls; return e; }
function toast(message) { $('toast').hidden = false; $('toast').textContent = message; clearTimeout(toastTimer); toastTimer = setTimeout(() => $('toast').hidden = true, 3500); }
function address(value) { const b = text('button', short(value), 'address'); b.title = 'Copy ' + value; b.addEventListener('click', () => navigator.clipboard.writeText(value).then(() => toast('Address copied')).catch(() => toast('Clipboard unavailable'))); return b; }
function render(s) {
  ensurePaperUi(); state = s; renderProfit(s); $('mode').textContent = s.demo ? 'DEMO · OFFLINE' : s.paperActive ? 'PAPER · SIMULATION' : s.mode.toUpperCase() + ' MODE'; $('mode').classList.toggle('live', s.mode === 'live');
  $('clock').textContent = new Date(s.time).toLocaleTimeString([], { hour12: false });
  const exp = s.positions.reduce((n, p) => n + BigInt(p.cost), 0n);
  $('cash').textContent = sol(s.cash); $('pnl').textContent = (BigInt(s.dayPnl) >= 0n ? '+' : '') + sol(s.dayPnl);
  $('pnl').className = BigInt(s.dayPnl) < 0n ? 'negative' : 'positive'; $('exposure').textContent = sol(exp);
  $('capacity').textContent = s.positions.length + ' / ' + s.limits.positions; $('capacity-note').textContent = Math.max(0, s.limits.positions - s.positions.length) + ' slots available';
  $('position-count').textContent = s.positions.length + ' OPEN'; $('pause').disabled = busy || s.demo || s.stopping; $('pause').textContent = s.paperActive ? (s.paused ? 'Resume paper entries' : 'Pause paper entries') : s.demo ? 'Preview only' : s.paused ? 'Resume new entries' : 'Pause new entries'; if ($('auto')) { $('auto').disabled = busy || !s.paperActive || s.demo || s.stopping; $('auto').textContent = s.autoPaper ? 'Stop auto paper' : 'Start auto paper'; }
  const note = s.paperActive ? (s.autoPaper ? 'SMART AUTO PAPER ACTIVE · Entries require fresh quotes, liquidity, momentum, and confirmed safety approval. Every fill is saved to CSV; no transaction is sent.' : 'PAPER MODE · Uses live quotes but never sends a transaction. Rug checks and the one-trade-per-token rule still apply.') : s.demo ? 'OFFLINE PREVIEW · Sample data only. This preview cannot connect to a wallet or place trades.' : s.stopping ? 'Engine stopping. Open positions and pending orders are being preserved.' : s.halted ? 'SAFETY HALT · New entries are blocked. Operator resume cannot override this halt.' : s.paused ? 'New entries paused. Position monitoring and automatic exits remain active.' : !s.feed.healthy ? 'Waiting for a fresh, warmed-up market feed. New entries are blocked until the feed is ready.' : 'Engine monitoring markets. New entries remain subject to every configured risk check.';
  $('notice').textContent = s.connected === false && !s.paperActive ? 'Live market app · Trading engine is not running. Watch tokens here; no trades are being placed.' : note; $('notice').classList.toggle('warn', s.demo || s.halted || (!s.feed.healthy && !s.paperActive));
  $('feed').textContent = s.feed.healthy ? 'Healthy' : 'Waiting / stale'; $('feed-dot').classList.toggle('healthy', s.feed.healthy);
  $('entries').textContent = s.stopping ? 'Stopping' : s.halted ? 'Safety halted' : s.paused ? 'Paused by you' : s.feed.healthy ? 'Risk gated' : 'Waiting for feed';
  $('slot').textContent = s.feed.slot ? s.feed.slot.toLocaleString() : '—'; $('wallet').textContent = short(s.wallet); $('wallet').title = s.wallet;
  $('positions-body').replaceChildren(); $('positions-empty').hidden = !!s.positions.length;
  for (const p of s.positions) {
    const row = document.createElement('tr'), cell = document.createElement('td'), asset = text('div', '', 'asset');
    asset.append(text('span', p.mint.slice(0, 2).toUpperCase(), 'coin')); const name = document.createElement('div'); name.append(address(p.mint), text('small', Number.isFinite(Number(p.qty)) ? Math.round(Number(p.qty)).toLocaleString() + ' simulated units' : 'simulated units')); asset.append(name); cell.append(asset); row.append(cell);
    row.append(text('td', sol(p.cost))); const value = document.createElement('td');
    const fresh = p.mark && s.time - p.mark.at < 10000;
    value.append(text('span', p.mark ? sol(p.mark.value) : '—')); value.append(text('small', !p.mark ? 'Not yet quoted' : fresh ? 'Latest estimate' : 'Stale estimate')); row.append(value);
    row.append(text('td', p.stage + ' / 5')); row.append(text('td', p.panic ? 'Exit requested' : 'Monitoring', p.panic ? 'negative' : 'positive'));
    const action = document.createElement('td'); if (s.paperActive) { const b = text('button', 'Exit all'); b.className = 'paper-action'; b.addEventListener('click', async () => { b.disabled = true; try { render(await api('/api/paper', { action: 'sell', mint: p.mint, fraction: 10000 })); toast('Paper position exited'); } catch (e) { toast(e.message); b.disabled = false; } }); action.append(b); } else action.append(text('small', 'Engine managed')); row.append(action); $('positions-body').append(row);
  }
  const lane = $('pending'); if (lane) lane.replaceChildren(text('div', 'ORDER LANE', 'eyebrow'), text('strong', s.pending ? s.pending.side.toUpperCase() + ' · Awaiting chain outcome' : 'No pending order'), text('p', s.pending ? short(s.pending.mint) + ' · ' + Math.floor((s.time - s.pending.created) / 1000) + 's pending. ' + s.pending.reason : 'Ready for the next eligible execution.'));
  const percent = Number(exp * 10000n / BigInt(s.limits.exposure)) / 100; $('exposure-percent').textContent = percent.toFixed(1) + '%'; $('exposure-bar').value = Math.min(percent, 100);
  $('limits').replaceChildren();
  for (const [label, value] of [['Per entry', sol(s.limits.buy) + ' SOL'], ['Exposure cap', sol(s.limits.exposure) + ' SOL'], ['Daily realized loss cap', sol(s.limits.dailyLoss) + ' SOL'], ['Slippage cap', (s.limits.slippage / 100).toFixed(1) + '%'], ['Stop trigger', '−' + (s.limits.stop / 100).toFixed(1) + '%'], ['Max Jito tip', sol(s.limits.tip) + ' SOL']]) $('limits').append(text('dt', label), text('dd', value));
  if ($('strategies')) { $('strategies').replaceChildren(text('small', 'Strategy availability')); for (const strategy of (s.strategies || [])) { const row = text('div', '', 'status-row'); row.append(text('span', strategy.kind.replaceAll('-', ' ')), text('b', strategy.enabled ? 'Enabled' : 'Gated', strategy.enabled ? 'positive' : 'muted')); row.title = strategy.reason; $('strategies').append(row); } }
  $('events').replaceChildren();
  if (!s.events.length) $('events').append(text('p', 'No events yet. The engine will publish activity here.', 'muted'));
  for (const e of s.events.slice(0, 40)) {
    const row = text('div', '', 'event'), detail = document.createElement('div'); detail.append(text('b', e.event.replaceAll('_', ' ')), text('p', [e.mint && short(e.mint), e.side, e.reason, e.status].filter(Boolean).join(' · ') || 'Engine telemetry')); row.append(text('span', '', 'event-mark'), detail, text('time', new Date(e.time).toLocaleTimeString([], { hour12: false }))); $('events').append(row);
  }
  $('candidate-count').textContent = s.candidates.length; $('candidates').replaceChildren();
  if (!s.candidates.length) $('candidates').append(text('p', 'Watching for new launches.', 'muted'));
  for (const c of s.candidates.slice(0, 8)) { const row = text('div', '', 'candidate'); row.append(address(c.mint), text('small', c.devSold ? 'Creator sold' : c.buyers + ' buyers · ' + Math.floor(c.age / 1000) + 's')); $('candidates').append(row); }
  if(s.connected === false && !s.paperActive) {for(const id of ['cash','pnl','exposure','capacity']) $(id).textContent = '—'; $('capacity-note').textContent = 'Connect engine to track'; $('entries').textContent = 'Not running'; $('limits').replaceChildren(text('p','Start the configured engine to see your limits.','muted'));  $('pause').textContent = 'Engine not running';}
  $('updated').textContent = 'Updated ' + new Date(s.time).toLocaleTimeString();
  renderOrderWidget();
}
async function refresh() {
  try { const r = await fetch('/api/state', { headers: { 'x-dashboard-token': token }, signal: AbortSignal.timeout(4000) }); if (!r.ok) throw Error('Disconnected'); render(await r.json()); }
  catch (e) { console.error('Dashboard refresh failed', e); $('notice').textContent = 'Dashboard disconnected. The displayed data may be stale. Check the bot terminal.'; $('notice').classList.add('warn'); $('pause').disabled = true; $('updated').textContent = 'Connection lost'; }
  finally { setTimeout(refresh, 1500); }
}
$('pause').addEventListener('click', async () => {
  if (!state || busy || state.demo) return; busy = true; $('pause').disabled = true;
  try { const response = await fetch('/api/entries', { method: 'POST', headers: { 'content-type': 'application/json', 'x-dashboard-token': token }, body: JSON.stringify({ paused: !state.paused }), signal: AbortSignal.timeout(8000) }); const s = await response.json(); if (!response.ok) throw Error(s.error); render(s); toast(s.paused ? 'New entries paused' : 'Entry pause lifted; risk checks still apply'); }
  catch (e) { toast(e.message || 'Action failed'); } finally { busy = false; if (state) $('pause').disabled = state.demo || state.stopping; }
});
$('auto')?.addEventListener('click', async () => { if (!state || busy || !state.paperActive) return; busy = true; $('auto').disabled = true; try { const r = await fetch('/api/paper-auto', { method: 'POST', headers: { 'content-type': 'application/json', 'x-dashboard-token': token }, body: JSON.stringify({ enabled: !state.autoPaper }), signal: AbortSignal.timeout(8000) }); const next = await r.json(); if (!r.ok) throw Error(next.error); render(next); toast(next.autoPaper ? 'Auto paper trading started' : 'Auto paper trading stopped'); } catch (e) { toast(e.message || 'Auto paper action failed'); } finally { busy = false; if (state) $('auto').disabled = !state.paperActive || state.demo || state.stopping; } });
$('wallet').addEventListener('click', () => state && navigator.clipboard.writeText(state.wallet).then(() => toast('Wallet address copied')).catch(() => toast('Clipboard unavailable')));
document.querySelectorAll('nav a').forEach(a => a.addEventListener('click', () => { document.querySelectorAll('nav a').forEach(x => x.classList.remove('active')); a.classList.add('active'); }));


let market = null, activeTab = 'tokens', searchRows = null;
const quoteHistory = new Map();
const usd = n => n === null || n === undefined ? '—' : new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumSignificantDigits:5}).format(n);
const age = at => !at ? 'no update' : Math.max(0,Math.floor((Date.now()-at)/1000))+'s ago';
async function api(path, body) { const r = await fetch(path,{method:body?'POST':'GET',headers:{'x-dashboard-token':token,...(body?{'content-type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(15000)}); const data = await r.json(); if(!r.ok) throw Error(data.error || 'Source unavailable'); return data; }
function link(label,url) {const a=text('a',label);a.href=url;a.target='_blank';a.rel='noopener noreferrer';return a;}
function researchLinks(item) { const mint = encodeURIComponent(item.mint), pair = encodeURIComponent(item.pair || item.mint); return [
 ['DEX', 'https://dexscreener.com/solana/'+mint], ['Pump', 'https://pump.fun/coin/'+mint], ['Solsniffer', 'https://solsniffer.com/scanner/'+mint], ['Bubblemaps', 'https://app.bubblemaps.io/sol/token/'+mint], ['GMGN', 'https://gmgn.ai/sol/token/'+mint], ['Axiom', 'https://axiom.trade/t/'+mint], ['Photon', 'https://photon-sol.tinyastro.io/en/lp/'+pair], ['BullX', 'https://bullx.io/terminal?chainId=1399811149&address='+mint], ['Jupiter', 'https://jup.ag/swap/SOL-'+mint]
 ]; }
function rememberQuote(item) { if (!item || item.price === null || item.price === undefined || item.price <= 0) return; const old = quoteHistory.get(item.mint) || []; const at = item.at || Date.now(); if (!old.length || old[old.length - 1].price !== item.price) old.push({ price:item.price, at }); while (old.length > 30) old.shift(); quoteHistory.set(item.mint, old); }
function traceSvg(item) { const values = quoteHistory.get(item.mint) || []; if (values.length < 2) return '<div class="trace-label">Collecting live quote samples…</div>'; const prices=values.map(x=>x.price), min=Math.min(...prices), max=Math.max(...prices), span=max-min||max*.01||1; const points=prices.map((v,i)=>`${(i/(prices.length-1)*100).toFixed(2)},${(96-(v-min)/span*80).toFixed(2)}`).join(' '); return '<div class="trace-label">Live quote trace · '+values.length+' samples</div><svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="Recent live quote trace"><polyline points="'+points+'" fill="none" stroke="#00c2ff" stroke-width="2" vector-effect="non-scaling-stroke"/><polyline points="0,100 '+points+' 100,100" fill="rgba(0,194,255,.12)" stroke="none"/></svg>'; }
function selectToken(item) { if (!item || !item.mint) return; selectedToken=item; rememberQuote(item); $('analysis-state').textContent=item.price===null||item.price===undefined?'UNQUOTED':'LIVE QUOTE'; renderTokenAnalysis(); renderOrderWidget(); }
function renderTokenAnalysis() { const root=$('token-analysis'); if(!root) return; const item=selectedToken; if(!item){root.innerHTML='<div class="analysis-empty"><span>◉</span><h3>Select a token</h3><p>Choose a scanner row to inspect liquidity, momentum, safety, and external research.</p></div>';return;} const safeName=(item.name||'Unknown token').replace(/[<>&]/g,''); const safeSymbol=(item.symbol||'TOKEN').replace(/[<>&]/g,''); root.replaceChildren(); const identity=document.createElement('div');identity.className='selected-token'; const glyph=text('div',(item.symbol||'??').slice(0,2).toUpperCase(),'token-glyph');const copy=text('button',short(item.mint),'address');copy.title='Copy '+item.mint;copy.addEventListener('click',()=>navigator.clipboard.writeText(item.mint).then(()=>toast('Mint copied')).catch(()=>toast('Clipboard unavailable')));const copyWrap=document.createElement('div');copyWrap.append(text('h3',safeSymbol),text('p',safeName),copy);const price=text('div','', 'order-price');price.append(text('b',usd(item.price)),text('small','Live indexed quote'));identity.append(glyph,copyWrap,price);root.append(identity);const trace=document.createElement('div');trace.className='quote-trace';trace.innerHTML=traceSvg(item);root.append(trace);const metrics=document.createElement('div');metrics.className='analysis-metrics';for(const [label,value,cls] of [['Liquidity',usd(item.liquidity)],['24h volume',usd(item.volume)],['24h change',item.change==null?'—':item.change.toFixed(2)+'%',item.change<0?'negative':'positive'],['Market cap',usd(item.cap)],['DEX',item.dex||'—'],['Quote age',age(item.at)]]){const d=text('div','');d.append(text('small',label),text('b',value,cls));metrics.append(d)}root.append(metrics);const dock=text('div','', 'research-dock');dock.append(text('h3','Research dock · opens separately'));const links=text('div','', 'research-links');for(const [label,url] of researchLinks(item))links.append(link(label+' ↗',url));dock.append(links);root.append(dock);const safety=text('button','Run local safety scan','paper-action');safety.style.marginTop='14px';safety.addEventListener('click',()=>showRisk(item.mint));root.append(safety); }
function renderOrderWidget() { const root=$('order-widget'); if(!root || !state) return; const item=selectedToken; const limits=state.limits||{}; $('order-slippage').textContent=limits.slippage===undefined?'—':(limits.slippage/100).toFixed(1)+'%';$('order-priority').textContent=limits.priority===undefined?'—':sol(limits.priority)+' SOL';$('order-tip').textContent=limits.tip===undefined?'—':sol(limits.tip)+' SOL';$('order-stop').textContent=limits.stop===undefined?'—':'−'+(limits.stop/100).toFixed(1)+'%'; if(!item){root.replaceChildren(text('p','Select a quoted token to prepare a paper order.','muted'));return;} root.replaceChildren();const top=text('div','', 'order-token');const left=document.createElement('div');left.append(text('h3',item.symbol||'TOKEN'),text('p',(item.name||'Unknown token')+' · '+short(item.mint)));const price=text('div','', 'order-price');price.append(text('b',usd(item.price)),text('small',item.price===null||item.price===undefined?'Quote unavailable':'Indexed quote'));top.append(left,price);root.append(top);const meta=text('div','', 'order-meta');for(const [label,value] of [['Allocation',sol(limits.buy||'0')+' SOL'],['Capacity',state.positions.length+' / '+limits.positions],['Safety','Run scan before entry'],['Route',state.paperActive?'Paper simulator':'Engine managed']]){const row=text('span','');row.textContent=label;row.append(text('b',value));meta.append(row)}root.append(meta);const actions=text('div','', 'order-actions');const buy=text('button','Paper buy','buy');buy.disabled=!state.paperActive||item.price===null||item.price===undefined;buy.addEventListener('click',async()=>{buy.disabled=true;try{const next=await api('/api/paper',{action:'buy',mint:item.mint});render(next);toast('Paper position opened after safety check');}catch(e){toast(e.message);buy.disabled=false;}});const test=text('button','Test buy','test');test.disabled=!state.paperActive||item.price===null||item.price===undefined;test.addEventListener('click',async()=>{if(!confirm('Open a simulator-only paper position even if safety checks fail? No transaction will be signed or sent.'))return;test.disabled=true;try{const next=await api('/api/paper',{action:'test-buy',mint:item.mint});render(next);toast('Simulator test position opened');}catch(e){toast(e.message);test.disabled=false;}});actions.append(buy,test);root.append(actions); }
function renderMarket() {
 if(!market) return;
 $('sources').replaceChildren();
 for(const [key,label] of [['solana','Solana network'],['dex','DEX Screener'],['pump','Pump.fun · PumpPortal'],['kol','Kolscan snapshot']]) {
  const source=market.sources[key], stale=Date.now()-source.at>(key==='kol'?130000:75000), card=text('div','','source');
  card.append(text('small',label),text('b',source.state==='live'&&!stale?'● Connected':source.state==='connected'?'● Listening':stale&&source.at?'Stale data':source.state),text('small',key==='solana'&&market.network.slot?'Slot '+market.network.slot.toLocaleString()+' · '+age(source.at):age(source.at)));$('sources').append(card);
 }
 const kol = activeTab==='kol' && !searchRows;
 $('market-head').replaceChildren();const head=document.createElement('tr');for(const label of kol?['Trader / token','Action','SOL amount','Trade time','Explore']:['Token','Price','24h change','Liquidity','24h volume','Explore / save'])head.append(text('th',label));$('market-head').append(head);
 let rows=searchRows || (activeTab==='watches'?market.watches.map(m=>market.tokens.find(t=>t.mint===m)||{mint:m,name:'Awaiting price index',symbol:short(m)}):market[activeTab]);
 $('market-note').textContent=searchRows?'Search results · Solana only':kol?'Public Kolscan page snapshot, refreshed every 60 seconds · '+(market.kolWalletCount||0)+' tracked wallets loaded. Tracked addresses are a signal only, not a profitability claim.':activeTab==='launches'?'New token creation stream via PumpPortal. Launches may not yet have a price or liquidity listing.':'Prices refresh about every 30 seconds. Saved tokens remain in your local watchlist. Simulator test buys use live quotes but intentionally bypass token safety for paper mechanics only; they never sign or broadcast.';
 $('market-body').replaceChildren();
 if(!rows.length){const tr=document.createElement('tr'),td=text('td',activeTab==='watches'?'Your watchlist is empty. Save a token with ☆.':'Waiting for source data. Try searching for a token.');td.colSpan=6;tr.append(td);$('market-body').append(tr);}
 for(const item of rows){ if(!kol) rememberQuote(item); const tr=document.createElement('tr'),td=document.createElement('td');td.append(text('b',kol?item.name+' / '+item.symbol:item.symbol),text('small',kol?(item.tracked?'Tracked KOL · ':'')+short(item.wallet):item.name),address(item.mint));tr.append(td); if(!kol){tr.tabIndex=0;tr.dataset.tokenMint=item.mint;tr.dataset.selected=String(selectedToken?.mint===item.mint);tr.title='Select '+(item.symbol||'token')+' for analysis and paper execution';tr.addEventListener('click',e=>{if(e.target.closest('a,button'))return;selectToken(item);});tr.addEventListener('keydown',e=>{if(e.target===tr && (e.key==='Enter'||e.key===' ')){e.preventDefault();selectToken(item);}});}
  if(kol){tr.append(text('td',item.side.toUpperCase(),item.side==='buy'?'positive':'negative'),text('td',item.sol.toFixed(4)),text('td',new Date(item.at).toLocaleString()));}
  else {const quote=activeTab==='launches'&&!searchRows?market.tokens.find(t=>t.mint===item.mint)||item:item;tr.append(text('td',usd(quote.price)),text('td',quote.change==null?'—':quote.change.toFixed(2)+'%',quote.change<0?'negative':'positive'),text('td',usd(quote.liquidity)),text('td',usd(quote.volume)));}
  const actions=document.createElement('td');actions.className='market-actions';actions.append(link('Chart ↗','https://dexscreener.com/solana/'+encodeURIComponent(item.mint)),link('Pump ↗','https://pump.fun/coin/'+encodeURIComponent(item.mint)));if(kol)actions.append(link('Tx ↗','https://solscan.io/tx/'+encodeURIComponent(item.signature)));
  if(!kol && item.price !== null && item.price !== undefined) { const pb=text('button','Paper buy'); pb.className='paper-action'; pb.addEventListener('click',async()=>{pb.disabled=true;try{const next=await api('/api/paper',{action:'buy',mint:item.mint});render(next);toast('Paper position opened after safety check');}catch(e){toast(e.message);pb.disabled=false;}});actions.append(pb); const tb=text('button','Test buy'); tb.className='paper-action'; tb.title='Simulator only: bypasses token safety checks and never broadcasts'; tb.addEventListener('click',async()=>{if(!confirm('Open a simulator-only paper position even if safety checks fail? No transaction will be signed or sent.'))return;tb.disabled=true;try{const next=await api('/api/paper',{action:'test-buy',mint:item.mint});render(next);toast('Simulator test position opened');}catch(e){toast(e.message);tb.disabled=false;}});actions.append(tb); }
  if(!kol) { const rb=text('button','Safety'); rb.className='paper-action'; rb.addEventListener('click',()=>showRisk(item.mint)); actions.append(rb); }
  const saved=market.watches.includes(item.mint),b=text('button',saved?'★ Saved':'☆ Save');b.addEventListener('click',async()=>{b.disabled=true;try{market=await api('/api/watch',{mint:item.mint,enabled:!saved});renderMarket();}catch(e){toast(e.message);b.disabled=false;}});actions.append(b);tr.append(actions);$('market-body').append(tr);
 }
 if(selectedToken){const replacement=(market.tokens||[]).find(t=>t.mint===selectedToken.mint);if(replacement)selectedToken=replacement;renderTokenAnalysis();}
}
async function showRisk(mint){ const card=$('risk-card'); card.hidden=false; card.replaceChildren(text('b','Checking token safety…')); try { const r=await api('/api/risk?mint='+encodeURIComponent(mint)); card.replaceChildren(); const title=text('strong',(r.safe===true?'✓ Safety checks passed':r.safe===false?'⚠ Entry blocked by safety checks':'? Safety is incomplete'),'risk-'+(r.safe===true?'good':r.safe===false?'bad':'unknown')); card.append(title,text('span',' '+short(r.mint)+' · RugCheck '+(r.providers.rugcheck==='live'?'live':'unavailable'))); const dl=document.createElement('dl'); const rows=[['Authorities',r.authorities.status==='revoked'?'Mint + freeze revoked':r.authorities.status],['Token-2022',r.token2022.enabled?(r.token2022.extensions.join(', ')||'extensions present'):'SPL token'],['LP status',r.liquidity.state+(r.liquidity.lockedPct===null?'':' · '+r.liquidity.lockedPct.toFixed(1)+'% locked')],['Top 10 holders',r.holders.top10Bps===null?'Unknown':(r.holders.top10Bps/100).toFixed(1)+'%'],['Bundling / insiders',r.bundling.state+(r.bundling.insiders===null?'':' · '+r.bundling.insiders+' linked')]]; for(const [a,b] of rows){dl.append(text('dt',a),text('dd',b));} card.append(dl); if(r.risks.length) card.append(text('p',r.risks.slice(0,5).map(x=>x.level.toUpperCase()+': '+x.name).join(' · '),'risk-list')); card.append(link('Open RugCheck ↗',r.links.rugcheck),link('Solana Tracker ↗',r.links.tracker),link('Solscan ↗',r.links.solscan)); } catch(e){ card.replaceChildren(text('span','Safety check unavailable: '+e.message,'risk-unknown')); } }
async function refreshMarket(){try{market=await api('/api/market');renderMarket();}catch{$('market-note').textContent='Live market service is unavailable on this screen. Open the app on port 8788.';}finally{setTimeout(refreshMarket,5000);}}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{activeTab=b.dataset.tab;searchRows=null;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('selected',x===b));renderMarket();}));
$('search-form').addEventListener('submit',async e=>{e.preventDefault();const q=$('query').value.trim();if(!q)return;const b=e.currentTarget.querySelector('button');b.disabled=true;try{searchRows=await api('/api/search?q='+encodeURIComponent(q));renderMarket();}catch(e){toast(e.message);}finally{b.disabled=false;}});
$('clear-search').addEventListener('click',()=>{searchRows=null;$('query').value='';renderMarket();});
function renderProfit(s){
 const report=s.performance, tracked=!!report?.count;
 $('profit-mode').textContent=s.paperActive?'PAPER · SIMULATED':s.connected===false?'NO ENGINE':s.demo?'DEMO':s.mode==='paper'?'PAPER · SIMULATED':'LIVE · RECORDED';
 $('profit-note').textContent=tracked?'Tracking since '+new Date(report.since).toLocaleString()+' · '+report.count+' recorded outcomes.' : s.paperActive ? 'Paper account ready · use Paper buy or Start auto paper. CSV logging is active.' : 'No trades recorded. Profit appears after the engine records fills.'; if (s.paperActive && s.csvFile) $('profit-note').textContent += ' · CSV: ' + s.csvFile;
 let unrealized=0n,marked=0,stale=0;
 for(const p of s.positions){if(!p.mark){stale++;continue;} marked++; unrealized+=BigInt(p.mark.value)-BigInt(p.cost); if(s.time-p.mark.at>=10000)stale++;}
 const canEstimate = tracked && marked > 0;
 for(const [id,value] of [['realized',tracked?BigInt(report.realized):null],['unrealized',canEstimate?unrealized:null],['combined',canEstimate?BigInt(report.realized)+unrealized:null]]){$(id).textContent=value===null?'—':sol(value);$(id).className=value===null?'':value<0n?'negative':'positive';}
 if (s.paperActive && stale > 0 && canEstimate) $('profit-note').textContent += ' · ' + stale + ' mark' + (stale === 1 ? '' : 's') + ' stale; estimate uses available quotes.';
 $('fills').replaceChildren();for(const f of (report?.fills||[]).slice(-12).reverse()){const row=text('div','','event'),amount=f.net ?? f.lamports ?? '0';row.append(text('span',f.side==='sell'?'↗':'•'),text('b',f.side.toUpperCase()+' '+short(f.mint)+' · '+(f.side==='buy'?'Spent '+sol(-BigInt(amount))+' SOL':'Net realized '+sol(f.pnl)+' SOL')),text('time',new Date(f.at).toLocaleString()));$('fills').append(row);}
}

refresh(); refreshMarket();

// Keep selection and navigation visible without rebuilding a focused row.
document.addEventListener('click', updateSelectionAccessibility);
document.addEventListener('keyup', updateSelectionAccessibility);
function updateSelectionAccessibility() {
 document.querySelectorAll('[data-token-mint]').forEach(row => { row.dataset.selected=String(row.dataset.tokenMint===selectedToken?.mint); });
 document.querySelectorAll('[data-tab]').forEach(button => button.setAttribute('aria-pressed',String(button.dataset.tab===activeTab)));
}
function updateNavigation() {
 const hash=location.hash || '#markets';
 document.querySelectorAll('nav a').forEach(link => { const current=link.getAttribute('href')===hash; link.classList.toggle('active',current); if(current)link.setAttribute('aria-current','location');else link.removeAttribute('aria-current'); });
}
window.addEventListener('hashchange',updateNavigation);
updateNavigation(); updateSelectionAccessibility();
